name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            elteikthesis_en.tex
          latexmk_shell_escape: true
      - name: Upload the compiled pdf
        uses: actions/upload-artifact@v3
        with:
          name: thesis-pdflatex
          path: |
            elteikthesis_en.pdf
          if-no-files-found: error
