name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            thesis.tex
          latexmk_shell_escape: true

# read email and name from the secret
      - name: commit
        run: git config --global user.email "${{ secrets.EMAIL }}" ;
          git config --global user.name "${{ secrets.NAME }}" ;
          git add thesis.pdf ;
          git commit -m "Add compiled pdf"
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}